### ISSUE TITLE
errore download kernel

### ISSUE THREAD

**Issue by ferramroberto** [aleritty/kernelupdate#4]
script non scarica i pacchetti dando questo errore
Riutilizzo della connessione esistente a kernel.ubuntu.com:80.
Richiesta HTTP inviata, in attesa di risposta... 404 Not Found
2014-08-02 09:40:36 ERRORE 404: Not Found.

l'errore è dovuto alla rilevazione del link del pacchetto deb errata dato che in questo caso trova
http://kernel.ubuntu.com/~kernel-ppa/mainline/v3.15.8-utopi/linux-headers-3.15.8-031508_3.15.8-031508.201407311933_all.deb
aggiungendo _3.15.8-031508.201407311933 al link

**Comment by ghost** [comment]
Il problema non è questo ferramroberto ma è in una delle fasi di substringing. Se si guardano i link generati infatti si nota che manca una "c" alla fine della parola utopiC nel mezzo dell'url (../v3.15.8-utopi?/..). Il resto, lo script lo genera bene :+1:  Ho già inviato una pull request.. :smile:

**Comment by aleritty** [comment]
Mmmh, strano, sulla mia macchina andava... Eppure non avrebbe dovuto... In ogni caso faccio l'upgrade e testo! Grazie

**Comment by ferramroberto** [comment]
perfetto ora funziona :D

**Comment by aleritty** [comment]
Ma è assurdo... a me non funziona più invece, devo riportare quell'8!
