### ISSUE TITLE
Errore riga 144

### ISSUE THREAD

**Issue by lavieroscavone** [aleritty/kernelupdate#8]
Ciao dopo l'aggiornamento del kernel mi restituisce sempre "Qualcosa è andato storto durante l'installazione, leggi bene l'output sopra in cerca dell'errore e riparalo! Non riavviare fino a quando lo avrai fatto, oppure riavvia su un altro kernel!" controllando l'output trovo questo errore " ./kernel-update: riga 144: Selezionato: comando non trovato"

ciao

**Comment by aleritty** [comment]
Se non trova dpkg molto probabilmente non sei su una distribuzione ubuntu...

**Comment by lavieroscavone** [comment]
si ho ubuntu 15.04

**Comment by lavieroscavone** [comment]
se provo a dare manualmente quel comando mi da questo errore
dpkg: errore nell'elaborare l'archivio *.deb (--install):
 impossibile accedere all'archivio: File o directory non esistente
Si sono verificati degli errori nell'elaborazione:
 *.deb

**Comment by lavieroscavone** [comment]
Ciao scusa perché hai chiuso la mia issue

**Comment by aleritty** [comment]
Verificato, non sussiste.

**Comment by lavieroscavone** [comment]
A me lo da e non é la prima volta

**Comment by aleritty** [comment]
Le issue non sono il posto adatto a chiedere supporto, questo script è destinato ad utenti esperti come è scritto chiaramente nelle indicazioni.

Per richieste di supporto non si usano le issue.
